services:
  web:
    image: superrandres/nginx-certbot
    environment:
      - TZ='America/Guayaquil'
    volumes:
      - ./letsencrypt/:/etc/letsencrypt
      - ./nginx/conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    restart: always