server {
    server_name test.relyjs.com;
    client_max_body_size 10M;

    root /usr/share/nginx/html/;
    index maintance.html;

    location / {
        try_files $uri $uri/ =404;
    }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/test.relyjs.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/test.relyjs.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host ~* relyjs.com) {
        return 301 https://test.relyjs.com$request_uri;
    } # managed by Certbot

    listen 80;
    server_name test.relyjs.com;

    return 404; # managed by Certbot
}
